### ISSUE TITLE
error and warning limits in property steps should support null values

### ISSUE THREAD

**Issue by jdorko** [sibvisions/gauges#2]
Sometimes not all limits are required and thus not set. Anyway this should be covered correctly.
Consider max: 20,
for
steps: [null,null,null,18] - doesn´t work for values x < 18 (color should be colorOK, but is colorWarning)
steps: [2,null,null,18] - doesn´t work for values 2 < x < 18 (color should be colorOK, but is colorWarning)
steps: [null,4,16,null] - for every value colorError, even if no error limit set. colorWarning never shown

I realized while debugging, that ifs aren´t evaluated correctly with null values in getColor(value, steps) method.

Maybe you can use as inspiration our Swing implementation:
double value = Math.max(gauge.minValue, Math.min(gauge.maxValue, ((Number)dataRow.getValue(columnName)).doubleValue()));
                
                if (!Double.isNaN(gauge.minErrorValue) && value <= gauge.minErrorValue)
                {
                    ((RingPlot)plot).setSectionPaint("VALUE", LIGHT_RED);
                }
                else if (!Double.isNaN(gauge.minWarningValue) && value <= gauge.minWarningValue)
                {
                    ((RingPlot)plot).setSectionPaint("VALUE", LIGHT_ORANGE);
                }
                else if (!Double.isNaN(gauge.maxErrorValue) && value >= gauge.maxErrorValue)
                {
                    ((RingPlot)plot).setSectionPaint("VALUE", LIGHT_RED);
                }
                else if (!Double.isNaN(gauge.maxWarningValue) && value >= gauge.maxWarningValue)
                {
                    ((RingPlot)plot).setSectionPaint("VALUE", LIGHT_ORANGE);
                }
                else
                {
                    ((RingPlot)plot).setSectionPaint("VALUE", LIGHT_GREEN);
                }

**Comment by gimmixAT** [comment]
this should already be fixed by https://github.com/sibvisions/gauges/commit/08afc934849685d35441df88797e20485e6a4882
