### ISSUE TITLE
Additional property displayValue

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/gauges#3]
I've just implemented a multi-factor-authentication which uses a gauge as a timer, we want to display the remaining time in the middle of the ring gauge in the format "mm:ss". Currently only numbers are accepted in the value property.

It would be nice if there was an additional property for displaying values, like in my case instead of only seconds in "mm:ss" format and a property for calculating like the value property does right now.

**Comment by rjahn** [comment]
So, simple use a label/string and keep the value intern, if label is set?

**Comment by rjahn** [comment]
Simply change the label format and remove the value. The label itself is enough.

**Comment by rjahn** [comment]
The reactUI already sets the label (columnLabel) and also the vaadinUI sets the label. If you use the js chart library without react or vaadin, it's good enough to set the value as label?

**Comment by gimmixAT** [comment]
Currently there are `title`, `label` and `value`.   
- `title` is the title above the gauge
- `label` is the label next to the value inside the gauge
- `value` is the numeric value -> this can also not change

Possible ways we could solve this:  
1. add an option to hide the `value` -> solves this for arc & ring gauges
2. add an option for a transform function to convert the `value` into a readable form -> would be my preferred option from a widget pov
3. add an option to set a readable value

**Comment by rjahn** [comment]
hm... if label is set, why should we show the value as label?

Is there a difference between gauge types?

**Comment by gimmixAT** [comment]
![grafik](https://user-images.githubusercontent.com/1855152/165595218-ebb9ac4e-964f-4369-be23-b1dead485099.png)

Meter & Speedometer the label is above the value and obstructed by the needle

The label could contain a readable version of the value

**Comment by rjahn** [comment]
clear, so add an option to hide value (an internal property). and hide value for ring and flat mode.

**Comment by rjahn** [comment]
It's still possible to set the value as label in both gauges.

**Comment by gimmixAT** [comment]
Since it was quite straight forward I added both options: `hideValue` & `formatValue` in https://github.com/sibvisions/gauges/commit/76889f2eea234c7fcbd48b3b98f4b21dbc8fefa8

**Comment by rjahn** [comment]
hideValue is working and I guess formatValue also
