### ISSUE TITLE
vertical ring resize not working in Safari

### ISSUE THREAD

**Issue by rjahn** [sibvisions/gauges#4]
If I try to resize Safari (only height), the ring doesn't resize.... works in Chrome without problems.

see video:
https://user-images.githubusercontent.com/1307043/172796212-d881f99f-93c4-4742-8d7a-4e1edbe59853.mp4

**Comment by gimmixAT** [comment]
have you by any chance set the `height` option on the ring like in the demo? If you remove that the ring should autosize to its container

**Comment by rjahn** [comment]
The height is set to 100%

<img width="1623" alt="image" src="https://user-images.githubusercontent.com/1307043/193785450-49e79f99-b0a9-416d-b4cd-1cfa66387020.png">

The difference is that Chrome set the height correct and Safari doesn't

Chrome:

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/1307043/193785964-9731fd5e-5e3f-4256-8643-5e51da1c40db.png">

**Comment by rjahn** [comment]
doesn't work with safari 13.1 but works with 15.6. So I guess it's a browser problem.

**Comment by rjahn** [comment]
Browser update.
