### ISSUE TITLE
Changing max of ring not working

### ISSUE THREAD

**Issue by rjahn** [sibvisions/gauges#5]
If we change the max value of a ring, it won't change or it doesn't update the max - not sure.

Start with e.g. 300000 and after e.g. 3 seconds, change the max to 60000 -> the ring shows the value but doesn't recognize the new max.

**Comment by rjahn** [comment]
setting the same max again, works.

**Comment by gimmixAT** [comment]
how do you update the max value? If I do the following in a loop it updates correctly for me:

```
ring.update({
   max: Math.round(Math.random() * 100)
})
```

**Comment by rjahn** [comment]
forget this issue - the wrong library was used. Everything works as expected!
