### ISSUE TITLE
Axis label does not change when max or min is changed

### ISSUE THREAD

**Issue by mhandsteiner** [sibvisions/gauges#6]
In SpeedometerGauge and MeterGauge the axis label does not change, if max or min is changed in configuration and set with gauge.update(state.configurationJson);
Also the needle stays on wrong position, until the value changes in configuration.

**Comment by gimmixAT** [comment]
The labels should update now if the `max` value changes. A `min` value other than `0` currently isn't supported by any of the gauge types.

**Comment by mhandsteiner** [comment]
I opened a ticket for min value support (#7)

**Comment by rjahn** [comment]
Any updates here?

**Comment by gimmixAT** [comment]
should be fixed / implemented in master
